export default [
  {
    allResources: [
      'bindings',
      'componentstatuses',
      'configmaps',
      'endpoints',
      'events',
      'limitranges',
      'namespaces',
      'namespaces/finalize',
      'namespaces/status',
      'nodes',
      'nodes/proxy',
      'nodes/status',
      'persistentvolumeclaims',
      'persistentvolumeclaims/status',
      'persistentvolumes',
      'persistentvolumes/status',
      'pods',
      'pods/attach',
      'pods/binding',
      'pods/ephemeralcontainers',
      'pods/eviction',
      'pods/exec',
      'pods/log',
      'pods/portforward',
      'pods/proxy',
      'pods/status',
      'podtemplates',
      'replicationcontrollers',
      'replicationcontrollers/scale',
      'replicationcontrollers/status',
      'resourcequotas',
      'resourcequotas/status',
      'secrets',
      'serviceaccounts',
      'serviceaccounts/token',
      'services',
      'services/proxy',
      'services/status',
    ],
    safeResources: [
      'bindings',
      'componentstatuses',
      'configmaps',
      'endpoints',
      'events',
      'limitranges',
      'namespaces',
      'namespaces/finalize',
      'namespaces/status',
      'persistentvolumeclaims',
      'persistentvolumeclaims/status',
      'persistentvolumes',
      'persistentvolumes/status',
      'pods',
      'pods/attach',
      'pods/binding',
      'pods/ephemeralcontainers',
      'pods/eviction',
      'pods/exec',
      'pods/log',
      'pods/portforward',
      'pods/proxy',
      'pods/status',
      'podtemplates',
      'replicationcontrollers',
      'replicationcontrollers/scale',
      'replicationcontrollers/status',
      'resourcequotas',
      'resourcequotas/status',
      'serviceaccounts',
      'serviceaccounts/token',
      'services',
      'services/proxy',
      'services/status',
    ],
    adminResources: ['nodes', 'nodes/proxy', 'nodes/status', 'secrets'],
    configResources: [],
    clusterOperatorConfigResources: [],
    namespacedSet: new Set([
      'bindings',
      'configmaps',
      'endpoints',
      'events',
      'limitranges',
      'persistentvolumeclaims',
      'persistentvolumeclaims/status',
      'pods',
      'pods/attach',
      'pods/binding',
      'pods/ephemeralcontainers',
      'pods/eviction',
      'pods/exec',
      'pods/log',
      'pods/portforward',
      'pods/proxy',
      'pods/status',
      'podtemplates',
      'replicationcontrollers',
      'replicationcontrollers/scale',
      'replicationcontrollers/status',
      'resourcequotas',
      'resourcequotas/status',
      'secrets',
      'serviceaccounts',
      'serviceaccounts/token',
      'services',
      'services/proxy',
      'services/status',
    ]),
    models: [
      {
        apiVersion: 'v1',
        kind: 'Binding',
        namespaced: true,
        verbs: ['create'],
        plural: 'bindings',
        shortNames: undefined,
        crd: true,
        abbr: 'ABR',
        labelPlural: 'ABRs',
        path: 'bindings',
        id: '',
        label: 'Binding',
      },
      {
        apiVersion: 'v1',
        kind: 'ComponentStatus',
        namespaced: false,
        verbs: ['get', 'list'],
        shortNames: ['cs'],
        plural: 'componentstatuses',
        crd: true,
        abbr: 'ABR',
        labelPlural: 'ABRs',
        path: 'componentstatuses',
        id: '',
        label: 'ComponentStatus',
      },
      {
        apiVersion: 'v1',
        kind: 'ConfigMap',
        namespaced: true,
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['cm'],
        plural: 'configmaps',
        crd: true,
        abbr: 'ABR',
        labelPlural: 'ABRs',
        path: 'configmaps',
        id: '',
        label: 'ConfigMap',
      },
      {
        apiVersion: 'v1',
        kind: 'Endpoints',
        namespaced: true,
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['ep'],
        plural: 'endpoints',
        crd: true,
        abbr: 'ABR',
        labelPlural: 'ABRs',
        path: 'endpoints',
        id: '',
        label: 'Endpoints',
      },
      {
        apiVersion: 'v1',
        kind: 'Event',
        namespaced: true,
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['ev'],
        plural: 'events',
        crd: true,
        abbr: 'ABR',
        labelPlural: 'ABRs',
        path: 'events',
        id: '',
        label: 'Event',
      },
      {
        apiVersion: 'v1',
        kind: 'LimitRange',
        namespaced: true,
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['limits'],
        plural: 'limitranges',
        crd: true,
        abbr: 'ABR',
        labelPlural: 'ABRs',
        path: 'limitranges',
        id: '',
        label: 'LimitRange',
      },
      {
        apiVersion: 'v1',
        kind: 'Namespace',
        namespaced: false,
        verbs: ['create', 'delete', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['ns'],
        plural: 'namespaces',
        crd: true,
        abbr: 'ABR',
        labelPlural: 'ABRs',
        path: 'namespaces',
        id: '',
        label: 'Namespace',
      },
      {
        apiVersion: 'v1',
        kind: 'Node',
        namespaced: false,
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['no'],
        plural: 'nodes',
        crd: true,
        abbr: 'ABR',
        labelPlural: 'ABRs',
        path: 'nodes',
        id: '',
        label: 'Node',
      },
      {
        apiVersion: 'v1',
        kind: 'PersistentVolumeClaim',
        namespaced: true,
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['pvc'],
        plural: 'persistentvolumeclaims',
        crd: true,
        abbr: 'ABR',
        labelPlural: 'ABRs',
        path: 'persistentvolumeclaims',
        id: '',
        label: 'PersistentVolumeClaim',
      },
      {
        apiVersion: 'v1',
        kind: 'PersistentVolume',
        namespaced: false,
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['pv'],
        plural: 'persistentvolumes',
        crd: true,
        abbr: 'ABR',
        labelPlural: 'ABRs',
        path: 'persistentvolumes',
        id: '',
        label: 'PersistentVolume',
      },
      {
        apiVersion: 'v1',
        kind: 'Pod',
        namespaced: true,
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['po'],
        plural: 'pods',
        crd: true,
        abbr: 'ABR',
        labelPlural: 'ABRs',
        path: 'pods',
        id: '',
        label: 'Pod',
      },
      {
        apiVersion: 'v1',
        kind: 'PodTemplate',
        namespaced: true,
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        plural: 'podtemplates',
        crd: true,
        abbr: 'ABR',
        labelPlural: 'ABRs',
        path: 'podtemplates',
        shortNames: undefined,
        id: '',
        label: 'PodTemplate',
      },
      {
        apiVersion: 'v1',
        kind: 'ReplicationController',
        namespaced: true,
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['rc'],
        plural: 'replicationcontrollers',
        crd: true,
        abbr: 'ABR',
        labelPlural: 'ABRs',
        path: 'replicationcontrollers',
        id: '',
        label: 'ReplicationController',
      },
      {
        apiVersion: 'v1',
        kind: 'ResourceQuota',
        namespaced: true,
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['quota'],
        plural: 'resourcequotas',
        crd: true,
        abbr: 'ABR',
        labelPlural: 'ABRs',
        path: 'resourcequotas',
        id: '',
        label: 'ResourceQuota',
      },
      {
        apiVersion: 'v1',
        kind: 'Secret',
        namespaced: true,
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        plural: 'secrets',
        shortNames: undefined,
        crd: true,
        abbr: 'ABR',
        labelPlural: 'ABRs',
        path: 'secrets',
        id: '',
        label: 'Secret',
      },
      {
        apiVersion: 'v1',
        kind: 'ServiceAccount',
        namespaced: true,
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['sa'],
        plural: 'serviceaccounts',
        crd: true,
        abbr: 'ABR',
        labelPlural: 'ABRs',
        path: 'serviceaccounts',
        id: '',
        label: 'ServiceAccount',
      },
      {
        apiVersion: 'v1',
        kind: 'Service',
        namespaced: true,
        verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch'],
        shortNames: ['svc'],
        plural: 'services',
        crd: true,
        abbr: 'ABR',
        labelPlural: 'ABRs',
        path: 'services',
        id: '',
        label: 'Service',
      },
    ],
  },
];
